CREATE TABLE TB_CLIENTES(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CPF VARCHAR(11) NOT NULL UNIQUE,
    TELEFONE VARCHAR(11) NOT NULL UNIQUE,
    DATA_NASCIMENTO DATE,
    PONTOS INT,

    PRIMARY KEY(ID)

);