CREATE TABLE TB_PRODUTOS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    TIPO VARCHAR(7) NOT NULL,
    PRECO  DECIMAL(10, 2)NOT NULL,
    VALOR_EM_PONTOS INT,


    PRIMARY KEY(ID)
);