CREATE TABLE TB_FATURAS(
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CPF_CLIENTE VARCHAR(11),
    ID_VENDA BIGINT NOT NULL,
    TIPO  VARCHAR(7),
    DATA_PAGAMENTO DATE NOT NULL,
    VALOR_FATURA DECIMAL(10,2),
    PAGO_EM_PONTOS TINYINT(1) NOT NULL DEFAULT 0,

    PRIMARY KEY(ID)
);